### ISSUE TITLE
[Diary] 목표칼로리 설정

### ISSUE THREAD

**Issue by downmix** [huusz/Da-Da#136]
- [x] GET
- [x] 버튼제어
- [x] POST

**Comment by 22hyeseung** [comment]
능력자b

**Comment by downmix** [comment]
- GET diary/kcal
처음으로 접속시 해당날자(오늘날짜)에 day_log가 없으면 에러가 발생.
GET할때 아무것도 없거나 목표칼로리가 null 일경우, 가장 마지막에 입력한 목표칼로리를 insert or update 시켜줘야 할것으로 보임.
Front 에서 마지막 목표칼로리를 찾아 갱신할수없어서 서버에서 보정작업을 해야 한다.


- POST diary/kcal
~원인불명 오류~ 개발환경의 문제로 판단되어 개발환경 재구축
~포스트맨으로 post 요청 보내면 아래와 같이 knex 오류가 발생한다.~
~하지만 로컬 개발서버로 띄어서 확인해보면 정상동작하는것처럼 보인다.~
~일시적인 현상인지, 작업실수로 생긴건지 확인이 필요함.~
```
Unhandled rejection Error: Undefined binding(s) detected when compiling FIRST query: select `day_log_kcal`, `day_log_member_id`, date_format(day_log_diary_date, '%Y-%m-%d') as diary_date from `day_log` where `day_log_member_id` = ? and `day_log_diary_date` = ? limit ?
    at QueryCompiler_MySQL.toSQL (/home/ubuntu/Da-Da/backend/node_modules/knex/lib/query/compiler.js:131:13)
    at Builder.toSQL (/home/ubuntu/Da-Da/backend/node_modules/knex/lib/query/builder.js:115:44)
    at /home/ubuntu/Da-Da/backend/node_modules/knex/lib/runner.js:56:32
    at tryCatcher (/home/ubuntu/Da-Da/backend/node_modules/bluebird/js/release/util.js:16:23)
    at /home/ubuntu/Da-Da/backend/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/home/ubuntu/Da-Da/backend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/Da-Da/backend/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ubuntu/Da-Da/backend/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ubuntu/Da-Da/backend/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/Da-Da/backend/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/ubuntu/Da-Da/backend/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/home/ubuntu/Da-Da/backend/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/home/ubuntu/Da-Da/backend/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/home/ubuntu/Da-Da/backend/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/home/ubuntu/Da-Da/backend/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/Da-Da/backend/node_modules/bluebird/js/release/promise.js:693:18
```

**Comment by suhyeon** [comment]
get:/diary/kcal => 해결 
1. day_log 에서 최초로 입력된 kcal정보로 null이면 update, null이 아니면 기존 기록 리턴
